---
version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:026090548352:task-definition/today-tdf:1"
        LoadBalancerInfo:
          ContainerName: "spring"
          ContainerPort: 8080
